import '../models/product/product_model.dart';

/// خدمة المنتجات الوهمية للعرض والاختبار
class DummyProducts {
  static List<ProductModel> getProducts() {
    return [
      // ========== إلكترونيات ==========
      ProductModel(
        id: '1',
        title: 'آيفون 15 برو ماكس 256GB',
        description: 'أحدث إصدارات آبل مع معالج A17 Pro وكاميرا محسنة',
        price: 450000,
        oldPrice: 500000,
        images: [
          'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800',
          'https://images.unsplash.com/photo-1592750475338-5e1b428a43b5?w=800',
        ],
        category: 'electronics',
        subcategory: 'phones',
        rating: 4.8,
        reviews: 120,
        stock: 25,
        sellerName: 'متجر التقنية',
        isFeatured: true,
        isNew: false,
        discount: 10,
      ),
      ProductModel(
        id: '2',
        title: 'سامسونج جالاكسي S24 الترا',
        description: 'هاتف سامسونج الرائد مع قلم S Pen وشاشة AMOLED',
        price: 380000,
        oldPrice: 420000,
        images: [
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800',
          'https://images.unsplash.com/photo-1598327100006-d3c56b85ba1b?w=800',
        ],
        category: 'electronics',
        subcategory: 'phones',
        rating: 4.7,
        reviews: 95,
        stock: 30,
        sellerName: 'متجر سامسونج',
        isFeatured: true,
        isNew: true,
        discount: 9,
      ),
      ProductModel(
        id: '3',
        title: 'ماك بوك برو M3 14 بوصة',
        description: 'لابتوب آبل بمعالج M3 Pro و 18 ساعة بطارية',
        price: 850000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
          'https://images.unsplash.com/photo-1611181340348-1a0c4c0a0c0a?w=800',
        ],
        category: 'electronics',
        subcategory: 'laptops',
        rating: 4.9,
        reviews: 67,
        stock: 15,
        sellerName: 'متجر آبل',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '4',
        title: 'بلاي ستيشن 5 مع عصا تحكم',
        description: 'جهاز ألعاب الجيل الجديد مع قرص 825GB',
        price: 280000,
        oldPrice: 310000,
        images: [
          'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800',
        ],
        category: 'electronics',
        subcategory: 'gaming',
        rating: 4.9,
        reviews: 200,
        stock: 40,
        sellerName: 'متجر الألعاب',
        isFeatured: true,
        isNew: false,
        discount: 10,
      ),
      ProductModel(
        id: '5',
        title: 'سماعة أبل إيربودز برو 2',
        description: 'سماعة لاسلكية مع إلغاء ضوضاء نشط',
        price: 95000,
        oldPrice: 110000,
        images: [
          'https://images.unsplash.com/photo-1600294037681-c80b4cb9b434?w=800',
        ],
        category: 'electronics',
        subcategory: 'audio',
        rating: 4.8,
        reviews: 180,
        stock: 60,
        sellerName: 'متجر آبل',
        isFeatured: false,
        isNew: false,
        discount: 14,
      ),
      ProductModel(
        id: '6',
        title: 'ساعة أبل ووتش ألترا 2',
        description: 'ساعة ذكية للمغامرات مع GPS ودفاع',
        price: 220000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800',
        ],
        category: 'electronics',
        subcategory: 'watches',
        rating: 4.7,
        reviews: 89,
        stock: 35,
        sellerName: 'متجر آبل',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '7',
        title: 'تلفزيون سامسونج 65 بوصة 4K',
        description: 'تلفزيون ذكي بتقنية QLED و HDR10+',
        price: 350000,
        oldPrice: 400000,
        images: [
          'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
        ],
        category: 'electronics',
        subcategory: 'tv',
        rating: 4.6,
        reviews: 75,
        stock: 20,
        sellerName: 'متجر سامسونج',
        isFeatured: false,
        isNew: false,
        discount: 12,
      ),
      ProductModel(
        id: '8',
        title: 'آيباد برو 12.9 بوصة M2',
        description: 'لوحية آبل مع شريحة M2 وشاشة Liquid Retina XDR',
        price: 520000,
        oldPrice: 580000,
        images: [
          'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800',
        ],
        category: 'electronics',
        subcategory: 'tablets',
        rating: 4.9,
        reviews: 110,
        stock: 18,
        sellerName: 'متجر آبل',
        isFeatured: true,
        isNew: false,
        discount: 10,
      ),
      ProductModel(
        id: '9',
        title: 'كاميرا سوني A7 IV',
        description: 'كاميرا Mirrorless بدقة 33 ميجابكسل',
        price: 950000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
        ],
        category: 'electronics',
        subcategory: 'cameras',
        rating: 4.9,
        reviews: 45,
        stock: 8,
        sellerName: 'متجر الكاميرات',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '10',
        title: 'درون DJI Mini 3 Pro',
        description: 'درون صغير مع كاميرا 4K و 34 دقيقة طيران',
        price: 420000,
        oldPrice: 480000,
        images: [
          'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800',
        ],
        category: 'electronics',
        subcategory: 'drones',
        rating: 4.8,
        reviews: 62,
        stock: 12,
        sellerName: 'متجر الدرونز',
        isFeatured: false,
        isNew: false,
        discount: 12,
      ),

      // ========== أزياء وملابس ==========
      ProductModel(
        id: '11',
        title: 'عباية مطرزة فاخرة',
        description: 'عباية أنيقة مطرزة يدوياً بخيوط ذهبية',
        price: 45000,
        oldPrice: 55000,
        images: [
          'https://images.unsplash.com/photo-1590548784585-643d2b9f7b4b?w=800',
        ],
        category: 'fashion',
        subcategory: 'women',
        rating: 4.5,
        reviews: 88,
        stock: 45,
        sellerName: 'بيت الأزياء',
        isFeatured: true,
        isNew: false,
        discount: 18,
      ),
      ProductModel(
        id: '12',
        title: 'طقم رجالي كلاسيك',
        description: 'بدلة رسمية ثلاث قطع لون كحلي',
        price: 85000,
        oldPrice: 100000,
        images: [
          'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800',
        ],
        category: 'fashion',
        subcategory: 'men',
        rating: 4.7,
        reviews: 56,
        stock: 30,
        sellerName: 'بيت الأزياء',
        isFeatured: true,
        isNew: true,
        discount: 15,
      ),
      ProductModel(
        id: '13',
        title: 'حقيبة يد جلد طبيعي',
        description: 'حقيبة يد فاخرة من جلد طبيعي إيطالي',
        price: 35000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
        ],
        category: 'fashion',
        subcategory: 'accessories',
        rating: 4.8,
        reviews: 92,
        stock: 55,
        sellerName: 'بيت الأزياء',
        isFeatured: true,
        isNew: false,
        discount: 0,
      ),
      ProductModel(
        id: '14',
        title: 'نظارات شمسية رجالية',
        description: 'نظارات شمسية designer بإطار ذهبي',
        price: 18000,
        oldPrice: 25000,
        images: [
          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
        ],
        category: 'fashion',
        subcategory: 'accessories',
        rating: 4.6,
        reviews: 78,
        stock: 70,
        sellerName: 'متجر النظارات',
        isFeatured: false,
        isNew: false,
        discount: 28,
      ),
      ProductModel(
        id: '15',
        title: 'ساعة رولكس كوبي',
        description: 'ساعة فاخرة بنفسجية مع سوار جلد',
        price: 55000,
        oldPrice: 70000,
        images: [
          'https://images.unsplash.com/photo-1523275335684-37801b7b4d4b?w=800',
        ],
        category: 'fashion',
        subcategory: 'watches',
        rating: 4.9,
        reviews: 120,
        stock: 25,
        sellerName: 'متجر الساعات',
        isFeatured: true,
        isNew: true,
        discount: 21,
      ),
      ProductModel(
        id: '16',
        title: 'حذاء جلد رجالي فاخر',
        description: 'حذاء كلاسيكي من الجلد الطبيعي لونه أسود',
        price: 28000,
        oldPrice: 35000,
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
        ],
        category: 'fashion',
        subcategory: 'shoes',
        rating: 4.7,
        reviews: 95,
        stock: 40,
        sellerName: 'متجر الأحذية',
        isFeatured: false,
        isNew: false,
        discount: 20,
      ),
      ProductModel(
        id: '17',
        title: 'عباية سوداء فاخرة',
        description: 'عباية سوداء قصيرة أكمام فاخرة',
        price: 32000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
        ],
        category: 'fashion',
        subcategory: 'women',
        rating: 4.8,
        reviews: 134,
        stock: 60,
        sellerName: 'بيت الأزياء',
        isFeatured: true,
        isNew: false,
        discount: 0,
      ),
      ProductModel(
        id: '18',
        title: 'شنطة ظهر جلد',
        description: 'شنطة ظهر أنيقة للعمل والدراسة',
        price: 22000,
        oldPrice: 28000,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
        ],
        category: 'fashion',
        subcategory: 'bags',
        rating: 4.6,
        reviews: 67,
        stock: 35,
        sellerName: 'بيت الأزياء',
        isFeatured: false,
        isNew: true,
        discount: 21,
      ),
      ProductModel(
        id: '19',
        title: 'قفطان مغربي فاخر',
        description: 'قفطان مغربي مطرز بالذهب والفضة',
        price: 85000,
        oldPrice: 100000,
        images: [
          'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=800',
        ],
        category: 'fashion',
        subcategory: 'women',
        rating: 4.9,
        reviews: 45,
        stock: 15,
        sellerName: 'بيت الأزياء',
        isFeatured: true,
        isNew: true,
        discount: 15,
      ),
      ProductModel(
        id: '20',
        title: 'تيشيرت رجالي كأس',
        description: 'تيشيرت قطن بألوان متعددة',
        price: 8500,
        oldPrice: 12000,
        images: [
          'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
        ],
        category: 'fashion',
        subcategory: 'men',
        rating: 4.5,
        reviews: 200,
        stock: 150,
        sellerName: 'متجر الملابس',
        isFeatured: false,
        isNew: false,
        discount: 29,
      ),

      // ========== أثاث ومنزلية ==========
      ProductModel(
        id: '21',
        title: 'طاولة سفرة خشب زان',
        description: 'طاولة سفرة 8 أشخاص من خشب الزان الطبيعي',
        price: 180000,
        oldPrice: 220000,
        images: [
          'https://images.unsplash.com/photo-1530018607912-eff968a86f07?w=800',
        ],
        category: 'furniture',
        subcategory: 'tables',
        rating: 4.7,
        reviews: 42,
        stock: 10,
        sellerName: 'معرض الأثاث',
        isFeatured: true,
        isNew: false,
        discount: 18,
      ),
      ProductModel(
        id: '22',
        title: 'كنبة L-shape فاخرة',
        description: 'كنبة على شكل L من الجلد الطبيعي',
        price: 450000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
        ],
        category: 'furniture',
        subcategory: 'sofas',
        rating: 4.8,
        reviews: 65,
        stock: 8,
        sellerName: 'معرض الأثاث',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '23',
        title: 'سرير طفل خشبي',
        description: 'سرير طفل خشب pino مع حارس',
        price: 85000,
        oldPrice: 100000,
        images: [
          'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
        ],
        category: 'furniture',
        subcategory: 'beds',
        rating: 4.6,
        reviews: 38,
        stock: 15,
        sellerName: 'معرض الأثاث',
        isFeatured: false,
        isNew: false,
        discount: 15,
      ),
      ProductModel(
        id: '24',
        title: 'خزانة ملابس 3 أبواب',
        description: 'خزانة ملابس واسعة 3 أبواب بمرايا',
        price: 120000,
        oldPrice: 145000,
        images: [
          'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800',
        ],
        category: 'furniture',
        subcategory: 'storage',
        rating: 4.5,
        reviews: 55,
        stock: 12,
        sellerName: 'معرض الأثاث',
        isFeatured: false,
        isNew: true,
        discount: 17,
      ),
      ProductModel(
        id: '25',
        title: 'مكتب عمل خشبي',
        description: 'مكتب عمل أنيق مع أدراج وصناديق',
        price: 75000,
        oldPrice: 90000,
        images: [
          'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800',
        ],
        category: 'furniture',
        subcategory: 'office',
        rating: 4.7,
        reviews: 48,
        stock: 20,
        sellerName: 'معرض الأثاث',
        isFeatured: true,
        isNew: false,
        discount: 17,
      ),

      // ========== عقارات ==========
      ProductModel(
        id: '26',
        title: 'فيلا فاخرة في الساحل',
        description: 'فيلا 5 غرف نوم مع حديقة ومسبح',
        price: 45000000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
        ],
        category: 'real_estate',
        subcategory: 'villas',
        rating: 4.9,
        reviews: 15,
        stock: 2,
        sellerName: 'شركة العقارات',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '27',
        title: 'شقة 3 غرف في صنعاء',
        description: 'شقة فاخرة 3 غرف نوم في حي الستين',
        price: 8500000,
        oldPrice: 9500000,
        images: [
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        ],
        category: 'real_estate',
        subcategory: 'apartments',
        rating: 4.7,
        reviews: 28,
        stock: 5,
        sellerName: 'شركة العقارات',
        isFeatured: true,
        isNew: false,
        discount: 10,
      ),
      ProductModel(
        id: '28',
        title: 'أرض زراعية 5000 متر',
        description: 'أرض زراعية في حضرموت مع بئر مياه',
        price: 25000000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?w=800',
        ],
        category: 'real_estate',
        subcategory: 'land',
        rating: 4.5,
        reviews: 12,
        stock: 3,
        sellerName: 'شركة العقارات',
        isFeatured: false,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '29',
        title: 'محل تجاري في市中心',
        description: 'محل 50 متر في شارع رئيسي',
        price: 12000000,
        oldPrice: 14000000,
        images: [
          'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800',
        ],
        category: 'real_estate',
        subcategory: 'commercial',
        rating: 4.6,
        reviews: 20,
        stock: 4,
        sellerName: 'شركة العقارات',
        isFeatured: false,
        isNew: false,
        discount: 14,
      ),
      ProductModel(
        id: '30',
        title: 'شقة دوبلكس فاخرة',
        description: 'دوبلكس 4 غرف مع تراس و停车',
        price: 15000000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        ],
        category: 'real_estate',
        subcategory: 'apartments',
        rating: 4.8,
        reviews: 18,
        stock: 3,
        sellerName: 'شركة العقارات',
        isFeatured: true,
        isNew: false,
        discount: 0,
      ),

      // ========== سيارات ==========
      ProductModel(
        id: '31',
        title: 'تويوتا كورولا 2024',
        description: 'سيارة سيدان جديدة 2024 لون أبيض',
        price: 9500000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
        ],
        category: 'automotive',
        subcategory: 'cars',
        rating: 4.8,
        reviews: 45,
        stock: 4,
        sellerName: 'وكيل تويوتا',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '32',
        title: 'مرسيدس C200 2023',
        description: 'سيارة مرسيدس فاخرة 2023',
        price: 28000000,
        oldPrice: 32000000,
        images: [
          'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
        ],
        category: 'automotive',
        subcategory: 'cars',
        rating: 4.9,
        reviews: 30,
        stock: 2,
        sellerName: 'وكيل مرسيدس',
        isFeatured: true,
        isNew: false,
        discount: 12,
      ),
      ProductModel(
        id: '33',
        title: 'دراجة نارية هوندا',
        description: 'دراجة نارية CBR 600cc',
        price: 1800000,
        oldPrice: 2000000,
        images: [
          'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800',
        ],
        category: 'automotive',
        subcategory: 'motorcycles',
        rating: 4.7,
        reviews: 25,
        stock: 6,
        sellerName: 'معرض الدراجات',
        isFeatured: false,
        isNew: false,
        discount: 10,
      ),
      ProductModel(
        id: '34',
        title: 'بي إم دبليو X5 2024',
        description: 'سيارة BMW X5 دفع رباعي فاخرة',
        price: 45000000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
        ],
        category: 'automotive',
        subcategory: 'cars',
        rating: 4.9,
        reviews: 22,
        stock: 2,
        sellerName: 'وكيل BMW',
        isFeatured: true,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '35',
        title: 'جيب تويوتا لاند كروزر',
        description: 'جيب لاند كروزر 2023 دفع رباعي',
        price: 32000000,
        oldPrice: 35000000,
        images: [
          'https://images.unsplash.com/photo-1625231354161-8609b8a7ae1e?w=800',
        ],
        category: 'automotive',
        subcategory: 'cars',
        rating: 4.9,
        reviews: 35,
        stock: 3,
        sellerName: 'وكيل تويوتا',
        isFeatured: true,
        isNew: false,
        discount: 8,
      ),

      // ========== مطاعم وأغذية ==========
      ProductModel(
        id: '36',
        title: 'باقات حلول غذائية شهرية',
        description: 'باقة أسبوعية من الخضروات والفواكه الطازجة',
        price: 85000,
        oldPrice: 100000,
        images: [
          'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        category: 'food',
        subcategory: 'organic',
        rating: 4.6,
        reviews: 58,
        stock: 50,
        sellerName: 'متجر الغذاء الصحي',
        isFeatured: true,
        isNew: true,
        discount: 15,
      ),
      ProductModel(
        id: '37',
        title: 'قهوة يمنية فاخرة',
        description: 'قهوة يمنية محمصة من啡ارع شبام',
        price: 15000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800',
        ],
        category: 'food',
        subcategory: 'coffee',
        rating: 4.9,
        reviews: 120,
        stock: 200,
        sellerName: 'محل القهوة',
        isFeatured: true,
        isNew: false,
        discount: 0,
      ),
      ProductModel(
        id: '38',
        title: 'عسل سدر يمني أصلي',
        description: 'عسل سدر يمني طبيعي من حضرموت',
        price: 35000,
        oldPrice: 42000,
        images: [
          'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800',
        ],
        category: 'food',
        subcategory: 'honey',
        rating: 4.8,
        reviews: 85,
        stock: 100,
        sellerName: 'متجر العسل',
        isFeatured: false,
        isNew: false,
        discount: 17,
      ),
      ProductModel(
        id: '39',
        title: 'شوكولاتة بلجيكية فاخرة',
        description: 'علبة شوكولاتة بلجيكية 24 قطعة',
        price: 45000,
        oldPrice: 55000,
        images: [
          'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800',
        ],
        category: 'food',
        subcategory: 'chocolate',
        rating: 4.7,
        reviews: 65,
        stock: 80,
        sellerName: 'متجر الحلويات',
        isFeatured: false,
        isNew: true,
        discount: 18,
      ),
      ProductModel(
        id: '40',
        title: 'زيت زيتون إسباني',
        description: 'زيت زيتون بكر ممتاز 1 لتر',
        price: 28000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800',
        ],
        category: 'food',
        subcategory: 'oils',
        rating: 4.8,
        reviews: 92,
        stock: 120,
        sellerName: 'متجر الغذاء الصحي',
        isFeatured: true,
        isNew: false,
        discount: 0,
      ),

      // ========== رياضة ولياقة ==========
      ProductModel(
        id: '41',
        title: 'مزلاج تمارين متعددة',
        description: 'جهاز تمارين متكامل للصدر والكتف والظهر',
        price: 85000,
        oldPrice: 100000,
        images: [
          'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800',
        ],
        category: 'sports',
        subcategory: 'gym',
        rating: 4.6,
        reviews: 42,
        stock: 15,
        sellerName: 'متجر الرياضة',
        isFeatured: true,
        isNew: false,
        discount: 15,
      ),
      ProductModel(
        id: '42',
        title: 'دراجة تمرين منزلية',
        description: 'دراجة ثابتة مع شاشة رقمية',
        price: 65000,
        oldPrice: 80000,
        images: [
          'https://images.unsplash.com/photo-1626443993706-ed5b4959c592?w=800',
        ],
        category: 'sports',
        subcategory: 'gym',
        rating: 4.5,
        reviews: 35,
        stock: 20,
        sellerName: 'متجر الرياضة',
        isFeatured: false,
        isNew: true,
        discount: 19,
      ),
      ProductModel(
        id: '43',
        title: 'حذاء رياضي نايكي',
        description: 'حذاء جري نايك إير ماكس',
        price: 32000,
        oldPrice: 40000,
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
        ],
        category: 'sports',
        subcategory: 'shoes',
        rating: 4.8,
        reviews: 150,
        stock: 60,
        sellerName: 'متجر الأحذية',
        isFeatured: true,
        isNew: false,
        discount: 20,
      ),
      ProductModel(
        id: '44',
        title: 'طقم إضاءة حمام سباحة',
        description: 'طقم إضاءة LED للمسبح 4 قطع',
        price: 25000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
        ],
        category: 'sports',
        subcategory: 'swimming',
        rating: 4.4,
        reviews: 28,
        stock: 25,
        sellerName: 'معرض المسابح',
        isFeatured: false,
        isNew: false,
        discount: 0,
      ),
      ProductModel(
        id: '45',
        title: 'شنطة رياضية كبيرة',
        description: 'شنطة رياضية سعة 40 لتر مع حجرات',
        price: 18000,
        oldPrice: 22000,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
        ],
        category: 'sports',
        subcategory: 'accessories',
        rating: 4.6,
        reviews: 78,
        stock: 55,
        sellerName: 'متجر الرياضة',
        isFeatured: false,
        isNew: true,
        discount: 18,
      ),

      // ========== كتب وتعليم ==========
      ProductModel(
        id: '46',
        title: 'مجموعة كتب تطوير الذات',
        description: '5 كتب من أفضل الكتب مبيعاً',
        price: 35000,
        oldPrice: 50000,
        images: [
          'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800',
        ],
        category: 'books',
        subcategory: 'self_development',
        rating: 4.8,
        reviews: 95,
        stock: 40,
        sellerName: 'مكتبة Sanaa',
        isFeatured: true,
        isNew: false,
        discount: 30,
      ),
      ProductModel(
        id: '47',
        title: 'لوحة رسم احترافية',
        description: 'لوحة رسم مع أقلام فحم وملفات',
        price: 25000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
        ],
        category: 'books',
        subcategory: 'art',
        rating: 4.7,
        reviews: 42,
        stock: 30,
        sellerName: 'مكتبة الفنون',
        isFeatured: false,
        isNew: true,
        discount: 0,
      ),
      ProductModel(
        id: '48',
        title: 'قاموس عربي-إنجليزي',
        description: 'قاموس شامل 15000 كلمة',
        price: 12000,
        oldPrice: 18000,
        images: [
          'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
        ],
        category: 'books',
        subcategory: 'education',
        rating: 4.6,
        reviews: 65,
        stock: 50,
        sellerName: 'مكتبة Sanaa',
        isFeatured: false,
        isNew: false,
        discount: 33,
      ),
      ProductModel(
        id: '49',
        title: 'كورس برمجة Python',
        description: 'دورة تعلم Python من الصفر (DVD)',
        price: 15000,
        oldPrice: 25000,
        images: [
          'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800',
        ],
        category: 'books',
        subcategory: 'courses',
        rating: 4.9,
        reviews: 120,
        stock: 100,
        sellerName: 'مكتبة التقنية',
        isFeatured: true,
        isNew: false,
        discount: 40,
      ),
      ProductModel(
        id: '50',
        title: 'مصحف قطر',
        description: 'مصحف قطر بحجم متوسط طباعة فاخرة',
        price: 18000,
        oldPrice: null,
        images: [
          'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=800',
        ],
        category: 'books',
        subcategory: 'religious',
        rating: 4.9,
        reviews: 200,
        stock: 150,
        sellerName: 'مكتبة religious',
        isFeatured: true,
        isNew: false,
        discount: 0,
      ),
    ];
  }

  /// الحصول على المنتجات حسب الفئة
  static List<ProductModel> getProductsByCategory(String category) {
    return getProducts().where((p) => p.category == category).toList();
  }

  /// الحصول على المنتجات المميزة
  static List<ProductModel> getFeaturedProducts() {
    return getProducts().where((p) => p.isFeatured).toList();
  }

  /// الحصول على المنتجات الجديدة
  static List<ProductModel> getNewProducts() {
    return getProducts().where((p) => p.isNew).toList();
  }

  /// الحصول على المنتجات المخفضة
  static List<ProductModel> getDiscountedProducts() {
    return getProducts().where((p) => p.discount > 0).toList();
  }

  /// الحصول على منتج واحد
  static ProductModel? getProductById(String id) {
    try {
      return getProducts().firstWhere((p) => p.id == id);
    } catch (e) {
      return null;
    }
  }

  /// البحث في المنتجات
  static List<ProductModel> searchProducts(String query) {
    final lowercaseQuery = query.toLowerCase();
    return getProducts().where((p) {
      return p.title.toLowerCase().contains(lowercaseQuery) ||
          p.description.toLowerCase().contains(lowercaseQuery) ||
          p.category.toLowerCase().contains(lowercaseQuery);
    }).toList();
  }
}